### ISSUE TITLE
specific design and model

### ISSUE THREAD

**Issue by farmohh** [EMBL-Hentze-group/DEWSeq#3]
Hello,
Thank you very much for the great tool!
I have eCLIP dataset with two conditions (before and after treatment), 8 IP replicates plus SMI controls in replicates.
I would like to use DEWSeq to compare binding profile of a RBP at two different time points. 
I was wondering if the DEWSeq pipeline can be applied to search for differentially bindind regions between IP samples (not for a one-sided IP vs SMI comparison)?  If so, how can I make this comparison while accounting for the negative controls? What would be the design formula and model for this experiment? 

Here is the sample info:

Sample ID Condition1	Condition2
1	T0 A IP
2	T0B	IP
3	T0C	IP
4	T0 D	IP
5	T2 A	IP
6	T2B	IP
7	T2C	IP
8	T2 D	IP
9	T0 A	Input
10	T0B	Input
11	T0C	Input
12	T0 D	Input
13	T2 A	Input
14	T2B	Input
15	T2C	Input
16	T2 D	Input

The different condition are T0 or T2 (non-stimulated or stimulated).

So for example, 
“T0 A IP” is the non stimulated sample A with the IP
“T0 A input” is the same sample as before just the input

“T2 A IP” is the stimulated sample A with the IP
“T2 A input” is the same sample as before just the input

Thank you in davance!
All the best,

**Comment by sudeepsahadevan** [comment]
Hi @farmohh 

Thanks for using DEWSeq. If I understand your question, you would like to test whether there are any differentially bound regions between "T0 IP" samples vs "T2 IP samples", and you are not looking into testing between "T0 A IP" vs "T2 A IP", please clarify this. 

If you are looking to test between "T0 IP" samples vs "T2 IP samples", we would recommend not to disregard Input samples totally, but use them as a part of your design. The first strategy would be a 3 step analysis, that is
1. T0 IP vs T0 Input
2. T2 IP vs T2 Input
3. Compare 1 and 2 and find ids of regions that are common, not found in any 
This would be a simple binary comparison to see if any of T0 enriched regions are present in T2 enriched regions.

The second strategy would be  to test the ratio of ratios as it is done [here](https://support.bioconductor.org/p/79068/). This should be feasible as DEWSeq uses DESeq2 for statistical testing. We haven't tested it ourselves as we didn't have such a study design before, but we are happy to follow up/help with this.

Hope that helps.

Kind regards,
Sudeep.

**Comment by farmohh** [comment]
Hi Sudeep, 
Thank you very much for your kind answer, very helpful indeed.
yes, I want to see whether there are any differentially bound regions between "T0 IP" samples vs "T2 IP samples" and would love to go with the second strategy (the ratio of ratios). 

So my colData looks as such:
 Sample id	assay	condition	patient
1	IP	pre	A
2	IP	pre	B
3	IP	pre	C
4	IP	pre	D
5	IP	post	A
6	IP	post	B
7	IP	post	C
8	IP	post	D
9	SMI	pre	A
10	SMI	pre	B
11	SMI	pre	C
12	SMI	pre	D
13	SMI	post	A
14	SMI	post	B
15	SMI	post	C
16	SMI	post	D

my design is therefore: ~ assay + condition + assay:condition
As I have paired samples, I was wondering whether the sample should be treated as a random variable and be included in the design matrix as bellow or the first design is sufficient?
design = ~ patient + assay + condition + assay:condition

And I really appreciate your willingness to help us. I was wondering if I can share some data with you via email or I shall continue asking my questions here?
Thanks in advance.

**Comment by sudeepsahadevan** [comment]
Hi @farmohh 

My initial intuition is that this design:
` ~ assay + condition + assay:condition` will be better as you have at most 2 patients per condition when you use this design
` design = ~ patient + assay + condition + assay:condition`

I would have to stress at this point that we haven't done this before, the data we had so far were from simple case vs control experiments, so you might run into some issues. If you are willing to share data with us, we gladly welcome that. I'm assuming that the data is some your in-house experiments, so if you'd like to share the data, either you can post a sample of it here or use the contact email  which is: biohentze[at]embl[dot]de

Kind regards,
Sudeep.
