### ISSUE TITLE
question about annotObj  in DESeqDataSetFromSlidingWindows

### ISSUE THREAD

**Issue by LoneKnightz** [EMBL-Hentze-group/DEWSeq#6]
Hi, 

I followed the tutorial from Htseq-clip and generated everything. 

But the sliding windowed annotation file that Htseq-clip created is BED6 format. 

It cannot be used for DESeqDataSetFromSlidingWindows as annotObj. 

May I ask do you have any idea that can convert annotation  from Htseq-clip to DESeqDataSetFromSlidingWindows  recoginized annotObj ?

**Comment by Distue** [comment]
Hi,

Please use the htseq-clip mapToId function to convert the bed style
annotation to a format which can be parsed by DEWSeq.

The flow diagram at
https://htseq-clip.readthedocs.io/en/latest/ might help understanding the
workflow.

The Bed6 format is primarily useful for visual inspection and counting,
this additional step speeds up reading in large annotation files in R. We
will make sure to add an error and explanation to DEWSeq. Thank you for
bringing this up.

If you need anything else. Please feel free to contact us.

Best,
Tom

LoneKnightz ***@***.***> schrieb am Di., 29. Nov. 2022, 01:39:

**Comment by LoneKnightz** [comment]
Thanks for reply. It really helped and my question got solved. 

I followed the old flow diagram and I used wrong output file from Htseq-clip.
