### ISSUE TITLE
Snakemake workflow for preprocessing prior DEWseq

### ISSUE THREAD

**Issue by tbrittoborges** [EMBL-Hentze-group/DEWSeq#8]
Dear Thomas @Distue and Sudeep @sudeepsahadevan,

I hope this finds you both well. I remember you used to provide a snakemake workflow to preprocess eClip data; please correct me if I'm wrong on this. Is that available anywhere? Do you recommend any alternatives?

**Comment by sudeepsahadevan** [comment]
Hi @tbrittoborges 

Is this what you meant ?
https://github.com/EMBL-Hentze-group/DEWSeq_analysis_helpers/tree/master/htseq-clip_snakemake

**Comment by tbrittoborges** [comment]
Hi Sudeep, 
Thanks for the prompt answer. I was referring to processing the reads (reads to alignments) workflow. Maybe I misremember it.
